# Generated by Django 3.2.13 on 2022-07-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('char_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
            options={
                'verbose_name': "Today's currency",
                'verbose_name_plural': "Today's currency",
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('chat_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Telegram subscriber',
                'verbose_name_plural': 'Telegram subscribers',
            },
        ),
    ]
