# Generated by Django 3.2.13 on 2022-07-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrecord',
            name='order_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
