# Generated by Django 3.2.13 on 2022-07-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_club', '0002_alter_deliveryrecord_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrecord',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='price_in_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
